Park
KNR-Selfie/selfie_carolocup2020 pull request #29
Opened 2019-07-25 11:27 UTC by RafLit

2019-07-29 23:34 UTC, matszczygielski requested changes
Selfie_odometry powinno wejść jako oddzielny PR, ale już trudno...
Nie wiem czy było skanowane roslint'erem, jeśli nie to zrób to.

2019-07-29 23:34 UTC, matszczygielski commented on src/selfie_park/include/selfie_park/park_server.h
> +#define MAX_TURN 0.8
To powinny być parametry. Jeśli przejdziemy na v5 nikt nie będzie zmieniał tego tutaj w kodzie.

2019-07-29 23:34 UTC, matszczygielski commented on src/selfie_park/include/selfie_park/park_server.h
> +  void blinkLeft(bool a);
Zmienna `a` nic nie mówi

2019-07-29 23:34 UTC, matszczygielski commented on src/selfie_park/include/selfie_park/park_server.h
> +  float PARKING_SPEED;
Czemu nagle taki format?

2019-07-29 23:34 UTC, matszczygielski commented on src/selfie_park/include/selfie_park/park_server.h
> +  } actual_odom_position_, actual_parking_position_, parking_spot_position_, actual_back_odom_position_,
Może po 2 zmienne w linii, żeby ładniej wyglądało?

2019-07-29 23:34 UTC, matszczygielski commented on src/selfie_park/src/park_server.cpp
> +  else return true;
Dodaj klamry lub entery, bo nie jest to czytelne.

2019-07-29 23:34 UTC, matszczygielski commented on src/selfie_park/src/park_server.cpp
> +      ros::Duration(2).sleep();
Dodać jako parametr czas postoju

2019-07-29 23:34 UTC, matszczygielski commented on src/selfie_park/src/park_server.cpp
> +    case get_straight:
Wszędzie jest printowane parking_state, a tutaj nie.

2019-07-29 23:34 UTC, matszczygielski commented on src/selfie_park/src/park_server.cpp
> +      blinkRight(false);
Już w get_straight powinny zgasnąć światła

2019-07-29 23:34 UTC, matszczygielski commented on src/selfie_park/src/park_server.cpp
> +      blinkLeft(false);
Zarządzanie światłami powinno odbywać się na jednym poziomie, jeśli nie są one zmieniane wewnątrz funkcji. Przeniósłbym do switcha z parking_state.

2019-07-29 23:34 UTC, matszczygielski commented on src/selfie_park/src/park_server.cpp
> +      blinkLeft(true);
Zarządzanie światłami powinno odbywać się na jednym poziomie, jeśli nie są one zmieniane wewnątrz funkcji. Przeniósłbym do switcha z parking_state.

2019-07-29 23:34 UTC, matszczygielski commented on src/selfie_park/src/park_server.cpp
> +        blinkRight(false);
Zarządzanie światłami powinno odbywać się na jednym poziomie, jeśli nie są one zmieniane wewnątrz funkcji. Przeniósłbym do switcha z parking_state.

2019-07-29 23:34 UTC, Dobry123 commented on src/selfie_park/src/park_server.cpp
> +  as_.publishFeedback(feedback);
Bez sensu jak dla mnie ten feedback odległości. Za to brakuje ważniejszego - action_status

2019-07-29 23:34 UTC, Dobry123 commented on src/selfie_park/include/selfie_park/park_server.h
> +          actual_front_parking_position_, actual_laser_parking_position_;
Czy wszystkie z tych zmiennych są faktycznie do czegoś używane?

2019-08-06 22:27 UTC, matszczygielski approved these changes

2019-09-28 11:43 UTC, MKrasa approved these changes

2019-09-28 11:44 UTC, merged