Park drift
KNR-Selfie/selfie_carolocup2020 pull request #72
Opened 2020-01-21 15:00 UTC by RafLit

2020-01-22 15:35 UTC, matszczygielski requested changes
+ uporządkować te parametry tutaj, dynamics reconfigure i w pliku parameters.yaml. Niektórych już nie używamy (np. odom_to_laser)

2020-01-22 15:35 UTC, Dobry123 commented on src/selfie_park/src/park_server.cpp
> +  pnh_.param<float>("iter_distance",iter_distance_,0.2);
Wyrzucić ten parametr do launch/config/parameters.yaml i najlepiej też do dynamic reconfigure

2020-01-22 15:35 UTC, Dobry123 commented on src/selfie_park/src/park_server.cpp
> +        std::cout<<"go to parking spot"<<std::endl;
Wywalić te printowania

2020-01-22 15:35 UTC, Dobry123 commented on src/selfie_park/src/park_server.cpp
> +  back_target_ = 0.;
Może jeden parametr, który będzie określał odległość środka samochodu od zera układu (czyli tylnej osi) zamiast tych trzech? 
Wtedy zawsze będziemy chcieli się tak zatrzymać przy miejscu tak żeby środek samochodu == środek miejsca parkingowego - iter_distance

2020-01-22 15:35 UTC, Dobry123 commented on src/selfie_park/src/park_server.cpp
> +    park_spot_dist_ -= 1./2.*std::sin(max_turn_)*std::abs(actual_dist_ - prev_dist_);
Ten współczynnik chcemy jako parametr. w parameters.yaml i dynamics reconfigure

2020-01-22 15:35 UTC, Dobry123 commented on src/selfie_park/src/park_server.cpp
> +        if(park_spot_dist_ > 0.)
Tego ifa można wyrzucić na samą górę, żeby go nie dublować

2020-01-22 15:35 UTC, Dobry123 commented on src/selfie_park/src/park_server.cpp
> +            if(actual_dist_ > front_target_)
Tutaj jak już nie będzie front target to dałbym zmienną i dodawał do niej różnicę dystansu pomiędzy wywołaniami. Dla iteracji jazdy w przód sprawdzał czy ta zmienna osiągnęła już iter_distance, dla iteracji jazdy w tył sprawdzał czy nie jest mniejsza od 0. Dodatkowo w if'ie dodać zmienną bool określającą, która iteracja (przód czy tył) jest aktualnie wykonywana. 

Po wykonaniu parkowanie zmienić zmienną bool na przeciwną.

To sprawi, że jak skończymy powiedzmy na przejechaniu 0.05 w przód to przy wyjeżdżaniu zacznie od doprowadzenia tej zmiennej do 0 jazdą w tył. (czyli idealne odtworzenie sekwencji w tył).

2020-01-31 14:27 UTC, pktiuk commented
Popraw README.md, masz zduplikowany opis swojego node'a , poza tym nie wydaje mi się abyś miał wypisane wszystkie parametry.

2020-01-31 19:58 UTC, matszczygielski requested changes

2020-01-31 19:58 UTC, Dobry123 commented on src/selfie_park/cfg/park_server.cfg
Dodaj jeszcze delay i back_to_base

2020-01-31 19:58 UTC, Dobry123 commented on src/selfie_park/src/park_server.cpp
Dodaj back_to_base i delay

2020-02-04 23:50 UTC, RafLit commented
Wersja przetransferowana z "drama", testowana na workshopie

2020-02-08 10:12 UTC, MKrasa approved these changes

2020-02-08 10:13 UTC, merged